# Generated by Django 4.2.7 on 2024-05-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BidsCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='Listing',
        ),
    ]
