# Generated by Django 5.0.6 on 2024-05-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bidscategory_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Product',
        ),
    ]
